### ISSUE TITLE
AndroidManifest.xml uses `android:name="io.flutter.app.FutterApplication"`

### ISSUE THREAD

**Issue by eskri969** [1hanzla100/flutter-weather#1]
Android studio generates this error, which can be fixed with the following.

https://stackoverflow.com/questions/71019822/androidmanifest-xml-uses-androidname-io-flutter-app-futterapplication

**Comment by 1hanzla100** [comment]
@eskri969 This App is built on Flutterv1. Flutterv2 might causing error

**Comment by Vikkybliz** [comment]
Can I upgrade the app to Flutter 3

**Comment by 1hanzla100** [comment]
@Vikkybliz yea Sure. Feel Free to create PR
